apiVersion: v1
kind: Namespace
metadata:
  name: testnamespace
---
# Persistent Volume Claim for storing HTML files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage-pvc
  namespace: testnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ConfigMap with your custom HTML content
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-content
  namespace: testnamespace
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                text-align: center;
                padding: 50px;
                background-color: #f0f0f0;
            }
            .welcome-message {
                font-size: 2.5em;
                color: #333;
                margin-bottom: 20px;
            }
            .subtitle {
                font-size: 1.2em;
                color: #666;
            }
        </style>
    </head>
    <body>
        <div class="welcome-message">Hi Shahabuddin</div>
        <div class="subtitle">Welcome to the Nginx server!</div>
        <div class="subtitle">Data is persisted across pod restarts</div>
    </body>
    </html>
---
# Updated Deployment with persistence and custom content
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-storage-pvc
      - name: nginx-config
        configMap:
          name: nginx-html-content
          items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testnamespace
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: testnamespace
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: shahab.3.237.178.79.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
